### ISSUE TITLE
Finish API documentation

### ISSUE THREAD

**Issue by vickumar1981** [vickumar1981/stringdistance#1]
Need to put annotated comments in more files.  The docs are incomplete and could use more explanation of what each of the methods and parameters do.

**Comment by reneleft01** [comment]
hi there. I'd like to pitch in and help your community with documentation support if possible.

**Comment by vickumar1981** [comment]
@reneleft01   thanks.

to run the docs you use: `sbt doc`, assuming you have `sbt` setup - https://www.scala-sbt.org/1.0/docs/Setup.html

there's only a few places where the documentation is okay, but even there it can be improved:

https://github.com/vickumar1981/stringdistance/blob/master/src/main/scala/com/github/vickumar1981/stringdistance/package.scala#L7

https://github.com/vickumar1981/stringdistance/blob/master/src/main/scala/com/github/vickumar1981/stringdistance/StringDistance.scala#L6

https://github.com/vickumar1981/stringdistance/blob/master/src/main/scala/com/github/vickumar1981/stringdistance/StringSound.scala#L6

Everywhere else, documentation is needed, and particularly for the Java interface.

**Comment by rjseymour66** [comment]
Hi All,
Do you still need help with the documentation?  I didn't see that this issue is closed.

I am a professional technical writer and would like to assist, if that is still needed.

**Comment by vickumar1981** [comment]
Hi @rjseymour66 .

Definitely still need help with the documentation.  The repo is using scaladocs:  https://docs.scala-lang.org/overviews/scaladoc/for-library-authors.html .  Please feel free to shoot me an email or DM me on Twitter, vickumar1981.  Thank you also.

**Comment by rjseymour66** [comment]
Great!  I will take a closer look over the weekend and respond with any questions/suggestions.

**Comment by vickumar1981** [comment]
Started working on the documentation:  https://github.com/vickumar1981/stringdistance/pulls

Basic usage of scala docs:

- https://docs.scala-lang.org/overviews/scaladoc/for-library-authors.html
- https://docs.scala-lang.org/style/scaladoc.html

**Comment by vickumar1981** [comment]
Closing and creating separate issues per top level package:

https://github.com/vickumar1981/stringdistance/issues/30
https://github.com/vickumar1981/stringdistance/issues/31
https://github.com/vickumar1981/stringdistance/issues/32
https://github.com/vickumar1981/stringdistance/issues/33
https://github.com/vickumar1981/stringdistance/issues/34
