### ISSUE TITLE
The method is bug -> CommonStringDistanceAlgo.getCommonChars 

### ISSUE THREAD

**Issue by brainliu81** [vickumar1981/stringdistance#39]
def getCommonChars(s1: String, s2: String, halfLen: Int): String = {
    val commonChars = new StringBuilder()
    val strCopy = new StringBuilder(s2)
    var n = s1.length
    val m = s2.length
    s1.zipWithIndex.foreach{
      case (ch, chIndex) => {
        var foundIt = false
        var j = math.max(0, chIndex - halfLen)
        while (!foundIt && j <= Math.min(chIndex + halfLen, m - 1)) {
          if (strCopy(j) == ch) {
            foundIt = true
            commonChars.append(ch)
            strCopy.setCharAt(j, '\0')
          }
          j += 1
        }
      }}
    commonChars.toString
  }

**Comment by vickumar1981** [comment]
@brainliu81   do you have a test case that i can use to debug/fix this?  thanks.
