### ISSUE TITLE
Release for Scala 2.13

### ISSUE THREAD

**Issue by ronanM** [vickumar1981/stringdistance#41]

**Comment by vickumar1981** [comment]
:+1:  @ronanM, will target next build to include scala 2.13.0:  https://www.scala-lang.org/news/2.13.0

**Comment by vickumar1981** [comment]
@ronanM  sorry for taking so long on this issue.

i've been waiting for a scalatest release for 2.13 b/c it's a dependency for this project.  In Sept., they released an M1 release for scala 2.13, so I'll try that out and see if everything still works.

https://mvnrepository.com/artifact/org.scalatest/scalatest

i suppose i could also just force it to use a version of scalatest from 2.12, also, but i figured that if scalatest hasn't yet pushed a release for 2.13, and my project depends on that, better wait for the experts to upgrade first.

**Comment by vickumar1981** [comment]
Looks like everything is working except for the scoverage plugin:  https://github.com/scoverage/scalac-scoverage-plugin/pull/279.

Once that PR is merged, a 2.13 release is possible.

**Comment by vickumar1981** [comment]
@ronanM   published a version `1.1.5` that should work with scala 2.13.1.

let me know if it's okay to close the issue out.  thanks.

**Comment by vickumar1981** [comment]
Closing this issue.  Should be fixed in `1.1.5`.  Please feel free to re-open if there are any problems building with Scala 2.13.1.
