### ISSUE TITLE
Only supported starting with Android O

### ISSUE THREAD

**Issue by ayoubBouziane** [vickumar1981/stringdistance#43]
the library id very usefull, but it is only supported starting with Android O (--min-api 26) !

**Comment by vickumar1981** [comment]
@ayoubBouziane  thanks for reporting the issue.  do you know what a good workaround would be?

**Comment by vickumar1981** [comment]
would using the java 7 version of the jar work with android?  `stringdistance_2.11` is compiled for java 7.

**Comment by vickumar1981** [comment]
Not sure there's a good fix.  Thanks for letting me know.

More recent versions on maven will only be compiled with Java 8+ support in mind.
