### ISSUE TITLE
Add back compatibility with Scala 2.11

### ISSUE THREAD

**Issue by vickumar1981** [vickumar1981/stringdistance#50]
Spark EMR currently still uses the 2.11 compiler.  

This commit: https://github.com/vickumar1981/stringdistance/commit/7dfbb7606434ef7076ece421e6d9658907ebc3c8  dropped support for 2.11.

Add back in compatibility with Scala 2.11

**Comment by vickumar1981** [comment]
Pushed a 1.2.3-SNAPSHOT that is available for Scala 2.11:  https://oss.sonatype.org/content/repositories/snapshots/com/github/vickumar1981/stringdistance_2.11/1.2.3-SNAPSHOT/

Need to test that this works with Scala 2.11 and can merge into `master`.

**Comment by vickumar1981** [comment]
Addressed by https://github.com/vickumar1981/stringdistance/pull/51.

Version `1.2.3` should be cross-compiled for Scala 2.11, 2.12, & 2.13.

**Comment by mzhao577** [comment]
Hi Vic,

This is wonderful!   I will give it a test from my side and let you know
the testing result.

Have  wonderful weekends!

Max

**Comment by vickumar1981** [comment]
@mzhao577   Did the `1.2.3` version work for you with Scala 2.11?

**Comment by mzhao577** [comment]
Hi Vic,

I just tested 1 case that I used most, the levenshstein distance and
score.  It looks great.

I plan to run all the other tests listed in your GitHub testing cases.  I
am doing it now. I will get you updated once I got it ran.

Max

**Comment by vickumar1981** [comment]
Thanks Max.

If you do add any more algorithms, please feel free to PR the repo if you
think they'd be useful to others.

I'll probably be doing a few more updates in a couple of weeks - nothing
heavy, just adding more documentation and maybe putting scalafmt to
auto-format all the files.

Appreciate it.   Cheers.

Vic Kumar
vickumar@gmail.com

**Comment by mzhao577** [comment]
Hi Vic,

I was busy recently.  I will do more testing once I get more free time.

Your code is very useful.  Please keep it up!

If there are things I can do to help. Please do not hesitate to reach out
to me.

Thanks for your wonderful work!

Max
